version: '3.8'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: server
    depends_on:
      - mongo
<<<<<<< HEAD
    env_file:
      - ./server/.env
=======
>>>>>>> b4e577d (Update 3 docker-compose.yml file)
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - STRIPE_SECRET_KEY="sk_test_51QM5xCDvCdBpPMtcAvHfvdbXt2by4HcKOhNhChzLfsKD3eSc93PruBnwU1yaVkyaizoeA0kNmXjQ2htoPyCuy9UL002VhThALB"
    ports:
      - "4000:4000"

volumes:
  mongo_data:
